# Generated by Django 5.1.2 on 2024-11-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriMesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_mesin', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndonMesinApp.kategorimesin')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_role', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndonMesinApp.departemen')),
            ],
        ),
    ]
