# Generated by Django 5.1.2 on 2024-11-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMesinApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departemen',
            old_name='nama_departemen',
            new_name='departemen',
        ),
    ]
