# Generated by Django 4.2.16 on 2024-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMesinApp', '0002_rename_nama_departemen_departemen_departemen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesin',
            name='status',
            field=models.CharField(default='ready', max_length=255),
        ),
    ]
