# Generated by Django 4.2.16 on 2024-11-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMesinApp', '0003_mesin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mesin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndonMesinApp.mesin')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndonMesinApp.role')),
            ],
        ),
    ]
