# Generated by Django 4.2.16 on 2024-11-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMesinApp', '0004_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AndonMesinApp.kategorimesin'),
        ),
    ]
