# Generated by Django 4.2.16 on 2024-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMesinApp', '0006_rename_kategori_role_area_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='status',
            field=models.CharField(default='waiting', max_length=255),
        ),
    ]
